# Generated by Django 5.1 on 2024-11-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wraps', '0002_favorite'),
        ('wraps', '0002_rename_title_userwrap_wrap_type_and_more'),
    ]

    operations = [
    ]
