# Generated by Django 5.1.3 on 2024-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wraps', '0002_rename_title_userwrap_wrap_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrap',
            name='wrap_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
