# Generated by Django 5.1.1 on 2024-12-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wraps', '0003_merge_20241127_2251'),
        ('wraps', '0003_userwrap_wrap_name'),
    ]

    operations = [
    ]
