# Generated by Django 5.1.1 on 2024-12-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wraps', '0004_merge_20241201_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
